language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install python-libtorrent -qq"
install:
  - "pip install -r requirements.txt"
script:
  - "./run_tests.sh"
